//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySet
    {
        public int Id { get; set; }
        public string ShortName { get; set; }
        public string Adress { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
        public int IdAgent { get; set; }
    
        public virtual AgentsSet AgentsSet { get; set; }
    }
}
